# TODO: Improve this workflow to make it better
# for testing.

name: Build CI (Adwaita Backend)
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libadwaita-1-0 libadwaita-1-dev ninja-build
    
    - name: Configure CMake
      run: mkdir build && cd build/; cmake .. -DNVD_USE_GTK4=ON -DNVD_BUILD_STATIC=OFF -DNVDIALOG_MAXBUF=4096 -G "Ninja" -DWIN32_TARGET=OFF -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build
