name: Adwaita Backend Testing (Ubuntu)
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libgtk-4-1 ninja-build libgtk-4-dev libadwaita-1-0 libadwaita-1-dev libnotify-bin libnotify-dev
    
    - name: Configure CMake
      run: mkdir build && cd build/; cmake .. -DNVD_USE_GTK4=ON -DNVD_BUILD_STATIC=OFF -DNVDIALOG_MAXBUF=4096 -G "Ninja" -DWIN32_TARGET=OFF -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build
    - name: Install library
      run: sudo cmake --install ${{github.workspace}}/build/
    - name: Test
      run: cd ${{github.workspace}}/build/ && ctest || cat ${{github.workspace}}/build/Testing/Temporary/LastTest.log
